<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" ignored="2" total="6" passed="0">
  <reporter-output>
    <line>
      <![CDATA[<a href= '/Users/VibhorAgarwal/TGAF_Mobile/screenshots/loginTest2019-07-22-03-39-41.png'target='_blank' ><img src='/Users/VibhorAgarwal/TGAF_Mobile/screenshots/loginTest2019-07-22-03-39-41.png'>loginTest2019-07-22-03-39-41</a>]]>
    </line>
    <line>
      <![CDATA[<a href= '/Users/VibhorAgarwal/TGAF_Mobile/screenshots/loginTest12019-07-22-03-44-35.png'target='_blank' ><img src='/Users/VibhorAgarwal/TGAF_Mobile/screenshots/loginTest12019-07-22-03-44-35.png'>loginTest12019-07-22-03-44-35</a>]]>
    </line>
  </reporter-output>
  <suite name="Demo Test Suite" duration-ms="378644" started-at="2019-07-22T10:08:25Z" finished-at="2019-07-22T10:14:44Z">
    <groups>
    </groups>
    <test name="DemoTestHdfc" duration-ms="378644" started-at="2019-07-22T10:08:25Z" finished-at="2019-07-22T10:14:44Z">
      <class name="LoginTest">
        <test-method status="PASS" signature="before()[pri:0, instance:LoginTest@7d20d0b]" name="before" is-config="true" duration-ms="19507" started-at="2019-07-22T10:08:05Z" finished-at="2019-07-22T10:08:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before -->
        <test-method status="PASS" signature="classDataInitializer()[pri:0, instance:LoginTest@7d20d0b]" name="classDataInitializer" is-config="true" duration-ms="24" started-at="2019-07-22T10:08:25Z" finished-at="2019-07-22T10:08:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- classDataInitializer -->
        <test-method status="FAIL" signature="loginTest(java.lang.reflect.Method)[pri:0, instance:LoginTest@7d20d0b]" name="loginTest" duration-ms="80070" started-at="2019-07-22T10:08:25Z" description="Test case 1" finished-at="2019-07-22T10:09:45Z">
          <exception class="br.eti.kinoshita.testlinkjavaapi.util.TestLinkAPIException">
            <message>
              <![CDATA[The status code (n) provided is not valid!]]>
            </message>
            <full-stacktrace>
              <![CDATA[br.eti.kinoshita.testlinkjavaapi.util.TestLinkAPIException: The status code (n) provided is not valid!
at br.eti.kinoshita.testlinkjavaapi.BaseService.checkResponseError(BaseService.java:105)
at br.eti.kinoshita.testlinkjavaapi.BaseService.executeXmlRpcCall(BaseService.java:84)
at br.eti.kinoshita.testlinkjavaapi.TestCaseService.reportTCResult(TestCaseService.java:611)
at br.eti.kinoshita.testlinkjavaapi.TestLinkAPI.setTestCaseExecutionResult(TestLinkAPI.java:1034)
at utils.TestLinkUtil.setResult(TestLinkUtil.java:28)
at listener.TestListener.onTestSkipped(TestListener.java:87)
at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:61)
at org.testng.internal.Invoker.runTestListeners(Invoker.java:1389)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:636)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- br.eti.kinoshita.testlinkjavaapi.util.TestLinkAPIException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="initializeExtentTest(java.lang.reflect.Method)[pri:0, instance:LoginTest@7d20d0b]" name="initializeExtentTest" is-config="true" duration-ms="5" started-at="2019-07-22T10:08:25Z" finished-at="2019-07-22T10:08:25Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void LoginTest.loginTest(java.lang.reflect.Method) throws java.io.IOException,java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeExtentTest -->
        <test-method status="PASS" signature="initializeExtentTest(java.lang.reflect.Method)[pri:0, instance:LoginTest@7d20d0b]" name="initializeExtentTest" is-config="true" duration-ms="1" started-at="2019-07-22T10:09:36Z" finished-at="2019-07-22T10:09:36Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void LoginTest.loginTest(java.lang.reflect.Method) throws java.io.IOException,java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeExtentTest -->
        <test-method status="FAIL" signature="loginTest(java.lang.reflect.Method)[pri:0, instance:LoginTest@7d20d0b]" name="loginTest" duration-ms="1" started-at="2019-07-22T10:09:36Z" description="Test case 1" finished-at="2019-07-22T10:09:36Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[wrong number of arguments]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: wrong number of arguments
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:LoginTest@7d20d0b]" name="afterMethod" is-config="true" duration-ms="4354" started-at="2019-07-22T10:09:41Z" finished-at="2019-07-22T10:09:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginTest status=FAILURE method=LoginTest.loginTest(java.lang.reflect.Method)[pri:0, instance:LoginTest@7d20d0b] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[<a href= '/Users/VibhorAgarwal/TGAF_Mobile/screenshots/loginTest2019-07-22-03-39-41.png'target='_blank' ><img src='/Users/VibhorAgarwal/TGAF_Mobile/screenshots/loginTest2019-07-22-03-39-41.png'>loginTest2019-07-22-03-39-41</a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="FAIL" signature="loginTest1(java.lang.reflect.Method)[pri:0, instance:LoginTest@7d20d0b]" name="loginTest1" duration-ms="288400" started-at="2019-07-22T10:09:51Z" finished-at="2019-07-22T10:14:39Z">
          <exception class="br.eti.kinoshita.testlinkjavaapi.util.TestLinkAPIException">
            <message>
              <![CDATA[The status code (n) provided is not valid!]]>
            </message>
            <full-stacktrace>
              <![CDATA[br.eti.kinoshita.testlinkjavaapi.util.TestLinkAPIException: The status code (n) provided is not valid!
at br.eti.kinoshita.testlinkjavaapi.BaseService.checkResponseError(BaseService.java:105)
at br.eti.kinoshita.testlinkjavaapi.BaseService.executeXmlRpcCall(BaseService.java:84)
at br.eti.kinoshita.testlinkjavaapi.TestCaseService.reportTCResult(TestCaseService.java:611)
at br.eti.kinoshita.testlinkjavaapi.TestLinkAPI.setTestCaseExecutionResult(TestLinkAPI.java:1034)
at utils.TestLinkUtil.setResult(TestLinkUtil.java:28)
at listener.TestListener.onTestSkipped(TestListener.java:87)
at org.testng.internal.TestListenerHelper.runTestListeners(TestListenerHelper.java:61)
at org.testng.internal.Invoker.runTestListeners(Invoker.java:1389)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:636)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- br.eti.kinoshita.testlinkjavaapi.util.TestLinkAPIException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest1 -->
        <test-method status="PASS" signature="initializeExtentTest(java.lang.reflect.Method)[pri:0, instance:LoginTest@7d20d0b]" name="initializeExtentTest" is-config="true" duration-ms="0" started-at="2019-07-22T10:09:51Z" finished-at="2019-07-22T10:09:51Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void LoginTest.loginTest1(java.lang.reflect.Method) throws java.io.IOException,java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeExtentTest -->
        <test-method status="PASS" signature="initializeExtentTest(java.lang.reflect.Method)[pri:0, instance:LoginTest@7d20d0b]" name="initializeExtentTest" is-config="true" duration-ms="1" started-at="2019-07-22T10:14:30Z" finished-at="2019-07-22T10:14:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void LoginTest.loginTest1(java.lang.reflect.Method) throws java.io.IOException,java.lang.InterruptedException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initializeExtentTest -->
        <test-method status="FAIL" signature="loginTest1(java.lang.reflect.Method)[pri:0, instance:LoginTest@7d20d0b]" name="loginTest1" duration-ms="1" started-at="2019-07-22T10:14:30Z" finished-at="2019-07-22T10:14:30Z">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[wrong number of arguments]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: wrong number of arguments
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest1 -->
        <test-method status="PASS" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:LoginTest@7d20d0b]" name="afterMethod" is-config="true" duration-ms="4300" started-at="2019-07-22T10:14:35Z" finished-at="2019-07-22T10:14:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginTest1 status=FAILURE method=LoginTest.loginTest1(java.lang.reflect.Method)[pri:0, instance:LoginTest@7d20d0b] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[<a href= '/Users/VibhorAgarwal/TGAF_Mobile/screenshots/loginTest12019-07-22-03-44-35.png'target='_blank' ><img src='/Users/VibhorAgarwal/TGAF_Mobile/screenshots/loginTest12019-07-22-03-44-35.png'>loginTest12019-07-22-03-44-35</a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="closeDriver()[pri:0, instance:LoginTest@7d20d0b]" name="closeDriver" is-config="true" duration-ms="0" started-at="2019-07-22T10:14:44Z" finished-at="2019-07-22T10:14:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
        <test-method status="PASS" signature="tearDownSuite()[pri:0, instance:LoginTest@7d20d0b]" name="tearDownSuite" is-config="true" duration-ms="1324" started-at="2019-07-22T10:14:44Z" finished-at="2019-07-22T10:14:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDownSuite -->
      </class> <!-- LoginTest -->
    </test> <!-- DemoTestHdfc -->
  </suite> <!-- Demo Test Suite -->
</testng-results>
